mod naming;

use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use clarity::vm::analysis::contract_interface_builder::ContractInterface;

use naming::clarity_to_camel;

/// The TypeScript utility types file, bundled at compile time.
const TYPES_TS: &str = include_str!("../ts/types.ts");

/// Generate TypeScript ABI const files + utility types for the given contracts.
///
/// For each contract, outputs a `.ts` file containing the contract interface
/// serialized as `export const {name}Abi = { ... } as const;`.
/// Also copies the utility types file and generates an `index.ts`.
pub fn generate(
    contracts: &BTreeMap<String, &ContractInterface>,
    output_dir: &Path,
) -> Result<usize, String> {
    fs::create_dir_all(output_dir)
        .map_err(|e| format!("failed to create output directory: {e}"))?;

    let mut generated = Vec::new();

    for (contract_name, interface) in contracts {
        let json = serde_json::to_string_pretty(interface)
            .map_err(|e| format!("failed to serialize {contract_name}: {e}"))?;

        let const_name = format!("{}Abi", clarity_to_camel(contract_name));

        let content = format!(
            "// This file is auto-generated by clarinet typegen\n\
             // Contract: {contract_name}\n\
             \n\
             export const {const_name} = {json} as const;\n"
        );

        let file_path = output_dir.join(format!("{contract_name}.ts"));
        fs::write(&file_path, &content)
            .map_err(|e| format!("failed to write {}: {e}", file_path.to_string_lossy()))?;

        generated.push(contract_name.as_str());
    }

    // Write the utility types file
    let types_path = output_dir.join("types.ts");
    fs::write(&types_path, TYPES_TS)
        .map_err(|e| format!("failed to write types.ts: {e}"))?;

    // Generate index.ts
    let index_content = generate_index(&generated);
    let index_path = output_dir.join("index.ts");
    fs::write(&index_path, &index_content)
        .map_err(|e| format!("failed to write index.ts: {e}"))?;

    Ok(generated.len())
}

fn generate_index(contract_names: &[&str]) -> String {
    let mut output = String::new();
    writeln!(output, "// This file is auto-generated by clarinet typegen\n").unwrap();
    writeln!(output, "export * from \"./types\";").unwrap();
    for name in contract_names {
        writeln!(output, "export * from \"./{name}\";").unwrap();
    }
    output
}

#[cfg(test)]
mod tests {
    use clarity::types::StacksEpochId;
    use clarity::vm::analysis::contract_interface_builder::*;
    use clarity::vm::ClarityVersion;

    use super::*;

    fn make_interface(
        functions: Vec<ContractInterfaceFunction>,
        variables: Vec<ContractInterfaceVariable>,
        maps: Vec<ContractInterfaceMap>,
    ) -> ContractInterface {
        ContractInterface {
            functions,
            variables,
            maps,
            fungible_tokens: vec![],
            non_fungible_tokens: vec![],
            epoch: StacksEpochId::Epoch25,
            clarity_version: ClarityVersion::Clarity2,
        }
    }

    #[test]
    fn test_generates_as_const() {
        let interface = make_interface(
            vec![ContractInterfaceFunction {
                name: "increment".to_string(),
                access: ContractInterfaceFunctionAccess::public,
                args: vec![ContractInterfaceFunctionArg {
                    name: "step".to_string(),
                    type_f: ContractInterfaceAtomType::uint128,
                }],
                outputs: ContractInterfaceFunctionOutput {
                    type_f: ContractInterfaceAtomType::response {
                        ok: Box::new(ContractInterfaceAtomType::bool),
                        error: Box::new(ContractInterfaceAtomType::none),
                    },
                },
            }],
            vec![],
            vec![],
        );

        let dir = std::env::temp_dir().join("typegen_abi_test");
        let _ = fs::remove_dir_all(&dir);
        let mut contracts = BTreeMap::new();
        contracts.insert("counter".to_string(), &interface);

        let count = generate(&contracts, &dir).unwrap();
        assert_eq!(count, 1);

        let content = fs::read_to_string(dir.join("counter.ts")).unwrap();
        assert!(content.contains("export const counterAbi ="));
        assert!(content.contains("as const;"));
        assert!(content.contains("\"increment\""));
        assert!(content.contains("\"uint128\""));

        // types.ts should be present
        assert!(dir.join("types.ts").exists());

        // index.ts should re-export
        let index = fs::read_to_string(dir.join("index.ts")).unwrap();
        assert!(index.contains("export * from \"./types\";"));
        assert!(index.contains("export * from \"./counter\";"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_kebab_case_contract_name() {
        let interface = make_interface(vec![], vec![], vec![]);
        let dir = std::env::temp_dir().join("typegen_abi_kebab_test");
        let _ = fs::remove_dir_all(&dir);
        let mut contracts = BTreeMap::new();
        contracts.insert("simple-nft".to_string(), &interface);

        generate(&contracts, &dir).unwrap();

        let content = fs::read_to_string(dir.join("simple-nft.ts")).unwrap();
        assert!(content.contains("export const simpleNftAbi ="));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_complex_types_serialize() {
        let interface = make_interface(
            vec![ContractInterfaceFunction {
                name: "get-info".to_string(),
                access: ContractInterfaceFunctionAccess::read_only,
                args: vec![],
                outputs: ContractInterfaceFunctionOutput {
                    type_f: ContractInterfaceAtomType::tuple(vec![
                        ContractInterfaceTupleEntryType {
                            name: "owner".to_string(),
                            type_f: ContractInterfaceAtomType::principal,
                        },
                        ContractInterfaceTupleEntryType {
                            name: "balance".to_string(),
                            type_f: ContractInterfaceAtomType::optional(Box::new(
                                ContractInterfaceAtomType::uint128,
                            )),
                        },
                    ]),
                },
            }],
            vec![],
            vec![ContractInterfaceMap {
                name: "balances".to_string(),
                key: ContractInterfaceAtomType::principal,
                value: ContractInterfaceAtomType::list {
                    type_f: Box::new(ContractInterfaceAtomType::uint128),
                    length: 10,
                },
            }],
        );

        let dir = std::env::temp_dir().join("typegen_abi_complex_test");
        let _ = fs::remove_dir_all(&dir);
        let mut contracts = BTreeMap::new();
        contracts.insert("test".to_string(), &interface);

        generate(&contracts, &dir).unwrap();

        let content = fs::read_to_string(dir.join("test.ts")).unwrap();
        // Tuple with nested optional
        assert!(content.contains("\"tuple\""));
        assert!(content.contains("\"optional\""));
        assert!(content.contains("\"principal\""));
        // List in map value
        assert!(content.contains("\"list\""));

        let _ = fs::remove_dir_all(&dir);
    }
}
