/**
 * Regression tests for the notification queue in `server/src/common.ts`.
 * Notifications must reach the bridge one at a time, in the order they were
 * received, and exactly once - even when they pile up while a slow one
 * (`build_state` takes ~100ms) is in flight. The only entries that may be
 * dropped are queued didChanges a newer snapshot of the same document
 * supersedes.
 *
 *   pnpm run test:server
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  DidChangeTextDocumentNotification,
  DidCloseTextDocumentNotification,
  DidOpenTextDocumentNotification,
  DidSaveTextDocumentNotification,
  HoverRequest,
} from "vscode-languageserver";
import type { Connection } from "vscode-languageserver";

import { initConnection } from "../src/common.ts";

const URI = "file:///contracts/counter.clar";
const OTHER_URI = "file:///contracts/token.clar";

type Handler = (method: string, params: unknown) => unknown;
type NotificationParams = { textDocument: { uri: string; version?: number } };
// the bridge is generated by wasm-pack, it isn't always built
type LspVscodeBridge = Parameters<typeof initConnection>[1];

function deferred() {
  let resolve!: () => void;
  let reject!: (err: Error) => void;
  const promise = new Promise<void>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

/** Let the pending microtasks and timers run. */
function tick() {
  return new Promise((resolve) => setTimeout(resolve, 0));
}

/**
 * Wire `initConnection` to a fake connection and a bridge whose notifications
 * only settle when the test says so.
 */
function setup() {
  const calls: [string, NotificationParams][] = [];
  const pending: ReturnType<typeof deferred>[] = [];
  let onNotification!: Handler;
  let onRequest!: Handler;

  const connection = {
    onInitialize() {},
    onNotification(handler: Handler) {
      onNotification = handler;
    },
    onRequest(handler: Handler) {
      onRequest = handler;
    },
    listen() {},
  } as unknown as Connection;

  const bridge = {
    onNotification(method: string, params: NotificationParams) {
      calls.push([method, params]);
      const next = deferred();
      pending.push(next);
      return next.promise;
    },
    onRequest(method: string) {
      return `handled:${method}`;
    },
  } as unknown as LspVscodeBridge;

  initConnection(connection, bridge);

  return {
    /** The methods the bridge was called with, in call order. */
    get handled() {
      return calls.map(([method]) => method);
    },
    /** The documents the bridge was called with, in call order. */
    get handledUris() {
      return calls.map(([, params]) => params.textDocument.uri);
    },
    /** The document versions the bridge was called with, in call order. */
    get handledVersions() {
      return calls.map(([, params]) => params.textDocument.version);
    },
    /** Settle the n-th bridge call, in call order. */
    async settle(index: number, err?: Error) {
      const call = pending[index];
      assert.ok(call, `bridge call #${index} was never made`);
      if (err) call.reject(err);
      else call.resolve();
      await tick();
    },
    notify(method: string, uri = URI, version?: number) {
      onNotification(method, { textDocument: { uri, version } });
    },
    request(method: string) {
      return onRequest(method, {});
    },
  };
}

test("notifications queued during a slow one are all handled, in order", async () => {
  const server = setup();

  server.notify(DidSaveTextDocumentNotification.method);
  await tick();
  assert.deepEqual(server.handled, [DidSaveTextDocumentNotification.method]);

  // both land while didSave is still in the bridge
  server.notify(DidChangeTextDocumentNotification.method);
  server.notify(DidCloseTextDocumentNotification.method);
  await tick();
  assert.deepEqual(
    server.handled,
    [DidSaveTextDocumentNotification.method],
    "the bridge must not be called again while one call is in flight",
  );

  await server.settle(0);
  assert.deepEqual(server.handled, [
    DidSaveTextDocumentNotification.method,
    DidChangeTextDocumentNotification.method,
  ]);

  await server.settle(1);
  await server.settle(2);
  assert.deepEqual(server.handled, [
    DidSaveTextDocumentNotification.method,
    DidChangeTextDocumentNotification.method,
    DidCloseTextDocumentNotification.method,
  ]);
});

test("a notification the bridge rejects doesn't stall the queue", async () => {
  const server = setup();
  const warn = console.warn;
  console.warn = () => {};

  try {
    server.notify(DidOpenTextDocumentNotification.method);
    await tick();
    server.notify(DidSaveTextDocumentNotification.method);

    await server.settle(0, new Error("bridge failure"));
    assert.deepEqual(server.handled, [
      DidOpenTextDocumentNotification.method,
      DidSaveTextDocumentNotification.method,
    ]);

    await server.settle(1);
  } finally {
    console.warn = warn;
  }
});

test("requests are declined while the queue is busy, served once it drains", async () => {
  const server = setup();

  const hover = `handled:${HoverRequest.method}`;
  assert.equal(server.request(HoverRequest.method), hover);

  server.notify(DidSaveTextDocumentNotification.method);
  await tick();
  assert.equal(server.request(HoverRequest.method), null);

  await server.settle(0);
  assert.equal(server.request(HoverRequest.method), hover);
});

test("notifications for unsupported protocols are dropped", async () => {
  const server = setup();

  server.notify(DidOpenTextDocumentNotification.method, "github://owner/repo");
  server.notify(DidCloseTextDocumentNotification.method, "github://owner/repo");
  await tick();
  assert.deepEqual(server.handled, []);

  // dropping them must not leave the queue thinking it's busy
  server.notify(DidOpenTextDocumentNotification.method);
  await tick();
  assert.deepEqual(server.handled, [DidOpenTextDocumentNotification.method]);
  await server.settle(0);
});

const didChange = DidChangeTextDocumentNotification.method;

test("queued didChanges for one document collapse to the newest", async () => {
  const server = setup();

  server.notify(didChange, URI, 1);
  await tick();

  // a burst of keystrokes, all landing while version 1 is in the bridge
  server.notify(didChange, URI, 2);
  server.notify(didChange, URI, 3);
  server.notify(didChange, URI, 4);

  await server.settle(0);
  assert.deepEqual(
    server.handledVersions,
    [1, 4],
    "only the newest of the queued snapshots is worth analyzing",
  );

  await server.settle(1);
  assert.deepEqual(server.handledVersions, [1, 4], "the queue is drained");
});

test("a queued didChange never replaces the in-flight one", async () => {
  const server = setup();

  server.notify(didChange, URI, 1);
  await tick();
  assert.deepEqual(server.handledVersions, [1]);

  // version 1 is already in the bridge, it can't be taken back
  server.notify(didChange, URI, 2);
  await server.settle(0);
  assert.deepEqual(server.handledVersions, [1, 2]);
  await server.settle(1);
});

test("didChanges for different documents are all handled", async () => {
  const server = setup();

  server.notify(didChange, URI, 1);
  await tick();
  server.notify(didChange, OTHER_URI, 1);
  server.notify(didChange, URI, 2);
  // merges into the queued OTHER_URI entry, skipping over the URI one
  server.notify(didChange, OTHER_URI, 2);

  await server.settle(0);
  await server.settle(1);
  await server.settle(2);
  assert.deepEqual(server.handledUris, [URI, OTHER_URI, URI]);
  assert.deepEqual(server.handledVersions, [1, 2, 2]);
});

for (const barrier of [
  DidSaveTextDocumentNotification.method,
  DidCloseTextDocumentNotification.method,
  DidOpenTextDocumentNotification.method,
]) {
  test(`a ${barrier} between two didChanges blocks the merge`, async () => {
    const server = setup();

    server.notify(DidSaveTextDocumentNotification.method);
    await tick();
    server.notify(didChange, URI, 1);
    server.notify(barrier, URI);
    server.notify(didChange, URI, 2);

    for (let i = 0; i < 4; i++) await server.settle(i);
    assert.deepEqual(server.handled, [
      DidSaveTextDocumentNotification.method,
      didChange,
      barrier,
      didChange,
    ]);
    assert.deepEqual(server.handledVersions, [undefined, 1, undefined, 2]);
  });

  test(`a ${barrier} on another document doesn't block the merge`, async () => {
    const server = setup();

    server.notify(DidSaveTextDocumentNotification.method);
    await tick();
    server.notify(didChange, URI, 1);
    server.notify(barrier, OTHER_URI);
    server.notify(didChange, URI, 2);

    for (let i = 0; i < 3; i++) await server.settle(i);
    assert.deepEqual(server.handled, [
      DidSaveTextDocumentNotification.method,
      didChange,
      barrier,
    ]);
    assert.deepEqual(server.handledVersions, [undefined, 2, undefined]);
  });
}
