/**
 * Regression tests for the notification queue in `server/src/common.ts`.
 * Notifications must reach the bridge one at a time, in the order they were
 * received, and exactly once - even when they pile up while a slow one
 * (`build_state` takes ~100ms) is in flight.
 *
 *   pnpm run test:server
 *
 * The sources run as-is, on Node's type stripping, so no build is needed.
 * `server/package.json` can't be marked `"type": "module"` - the rspack
 * bundles it also contains are CommonJS - hence the `--disable-warning`
 * flag in the script, Node warns about reparsing every typeless `.ts`.
 */

import assert from "node:assert/strict";
import { test } from "node:test";
import { setTimeout as sleep } from "node:timers/promises";

import {
  DidChangeTextDocumentNotification,
  DidCloseTextDocumentNotification,
  DidOpenTextDocumentNotification,
  DidSaveTextDocumentNotification,
  HoverRequest,
} from "vscode-languageserver";
import type { Connection } from "vscode-languageserver";

import { initConnection } from "../src/common.ts";

const URI = "file:///contracts/counter.clar";
const READ_ONLY_URI = "github://owner/repo";

const didOpen = DidOpenTextDocumentNotification.method;
const didChange = DidChangeTextDocumentNotification.method;
const didClose = DidCloseTextDocumentNotification.method;
const didSave = DidSaveTextDocumentNotification.method;
const hover = HoverRequest.method;

type Handler = (method: string, params: unknown) => unknown;

/** Let the queue make whatever progress it can. */
const tick = () => sleep(0);

/**
 * Wire `initConnection` to a fake connection and to a bridge whose
 * notifications only settle when the test says so.
 */
function setup() {
  const handled: string[] = [];
  const inFlight: PromiseWithResolvers<void>[] = [];
  let onNotification!: Handler;
  let onRequest!: Handler;

  const connection = {
    onInitialize() {},
    onNotification(handler: Handler) {
      onNotification = handler;
    },
    onRequest(handler: Handler) {
      onRequest = handler;
    },
    listen() {},
  } as unknown as Connection;

  const bridge = {
    onNotification(method: string) {
      handled.push(method);
      const call = Promise.withResolvers<void>();
      inFlight.push(call);
      return call.promise;
    },
    onRequest(method: string) {
      return `handled:${method}`;
    },
    // the real bridge is generated by wasm-pack, it isn't always built
  } as unknown as Parameters<typeof initConnection>[1];

  initConnection(connection, bridge);

  return {
    handled,
    /** Let the oldest bridge call still in flight return. */
    async settle(err?: Error) {
      const call = inFlight.shift();
      assert.ok(call, "no bridge call in flight");
      if (err) call.reject(err);
      else call.resolve();
      await tick();
    },
    notify(method: string, uri = URI) {
      onNotification(method, { textDocument: { uri } });
    },
    request(method: string) {
      return onRequest(method, {});
    },
  };
}

test("notifications queued during a slow one are all handled, in order", async () => {
  const server = setup();

  server.notify(didSave);
  await tick();
  assert.deepEqual(server.handled, [didSave]);

  // both land while didSave is still in the bridge
  server.notify(didChange);
  server.notify(didClose);
  await tick();
  assert.deepEqual(
    server.handled,
    [didSave],
    "the bridge must not be called again while one call is in flight",
  );

  await server.settle();
  assert.deepEqual(server.handled, [didSave, didChange]);

  await server.settle();
  assert.deepEqual(server.handled, [didSave, didChange, didClose]);
});

test("a notification the bridge rejects doesn't stall the queue", async (t) => {
  const server = setup();
  t.mock.method(console, "warn", () => {});

  server.notify(didOpen);
  await tick();
  server.notify(didSave);

  await server.settle(new Error("bridge failure"));
  assert.deepEqual(server.handled, [didOpen, didSave]);
});

// declining requests while the bridge is busy is pre-existing policy, pinned
// here because it's the queue length that decides it
test("requests are declined while the queue is busy, served once it drains", async () => {
  const server = setup();

  assert.equal(server.request(hover), `handled:${hover}`);

  server.notify(didSave);
  await tick();
  assert.equal(server.request(hover), null);

  await server.settle();
  assert.equal(server.request(hover), `handled:${hover}`);
});

test("notifications for unsupported protocols are dropped", async () => {
  const server = setup();

  server.notify(didOpen, READ_ONLY_URI);
  server.notify(didClose, READ_ONLY_URI);
  await tick();
  assert.deepEqual(server.handled, []);

  // dropping them must not leave the queue thinking it's busy
  server.notify(didOpen);
  await tick();
  assert.deepEqual(server.handled, [didOpen]);
});
