packages:
  - "client"
  - "server"
  - "debug"

allowBuilds:
  '@playwright/browser-chromium': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  keytar: true

minimumReleaseAge: 7200 # 5 days in minutes
