packages:
  - "billboard"
  - "counter"
  - "simple-nft"
  - "swappool"

allowBuilds:
  esbuild: true

minimumReleaseAge: 4320

publicHoistPattern:
  - '@stacks/clarinet-sdk-wasm'

overrides:
  '@stacks/clarinet-sdk': 'link:../../../components/clarinet-sdk/node'
