# The clarinet-sdk is published to npm when a release is created.
# It's based on the pnpm workspace defined in pnpm-workspace.yaml at the root of the project.
# Two packages are built with wasm-pack - @stacks/clarinet-sdk-wasm and @stacks/clarinet-sdk-wasm-browser
# They need to be built first
# Then two packages are built with tsc - @stacks/clarinet-sdk and @stacks/clarinet-sdk-browser


name: Publish Clarinet SDK
on:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt --target wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Wasm packages
        run: pnpm run build:sdk-wasm

      - name: Publish sdk-wasm package
        run: pnpm --filter ./components/clarinet-sdk-wasm/pkg-node --filter ./components/clarinet-sdk-wasm/pkg-browser publish --access public

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build sdk package
        run: pnpm run build:sdk

      - name: Publish sdk package
        run: pnpm --filter ./components/clarinet-sdk/node --filter ./components/clarinet-sdk/browser publish --access public
